"use client";

import { useState } from "react";

export function FaqSection() {
  const faqs = [
    {
      q: "Can an empanelled hospital ask for an advance cash deposit for PMJAY treatment?",
      a: "No. Under PMJAY scheme guidelines, empanelled healthcare providers (EHCPs) must provide 100% cashless inpatient treatment for covered packages. Demanding advance deposits or out-of-pocket cash payments for covered procedures violates empanelment guidelines.",
    },
    {
      q: "What should I do if the hospital claims the insurance pre-authorisation portal is down?",
      a: "Emergency medical treatment cannot be delayed due to portal downtimes or administrative verification delays. Ask the hospital PMJAY kiosk (Ayushman Mitra desk) to log the pre-authorisation request and initiate emergency care immediately.",
    },
    {
      q: "Is this tool an official government service?",
      a: "No. PMJAY Advocate is an independent, free public-interest assistance tool. It matches your case against official National Health Authority (NHA) Health Benefit Package rates and prepares structured drafts that you can submit via the official Ayushman App (CGRMS).",
    },
    {
      q: "How do I file the draft complaint generated by this tool?",
      a: "You can copy the generated text or download the PDF document, and submit it directly through the official Centralized Grievance Redressal and Management System (CGRMS) via cgrms.pmjay.gov.in or the Ayushman Bharat mobile app.",
    },
    {
      q: "What if the hospital refuses to give a written denial reason?",
      a: "Use our 'Keep a Record' evidence tool on your case page to log the staff member's name, timestamp, and verbal statements. This timestamped evidence is embedded into your downloadable case PDF for official dispute filing.",
    },
  ];

  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section aria-labelledby="faq-title" className="space-y-6">
      <div className="text-center space-y-2">
        <p className="text-xs font-bold uppercase tracking-wider text-teal-800">
          Clear Answers to Critical Questions
        </p>
        <h2 id="faq-title" className="font-display text-2xl sm:text-3xl font-semibold tracking-tight-display text-teal-950">
          Frequently Asked Questions
        </h2>
        <p className="text-sm sm:text-base text-sand-900/70 max-w-xl mx-auto font-medium">
          Know your rights and standard operating procedures under the Ayushman Bharat scheme.
        </p>
      </div>

      <div className="space-y-3 pt-2">
        {faqs.map((faq, index) => {
          const isOpen = openIndex === index;
          return (
            <div
              key={index}
              className="glass-panel overflow-hidden transition-all"
            >
              <button
                type="button"
                onClick={() => setOpenIndex(isOpen ? null : index)}
                className="w-full flex items-center justify-between p-5 sm:p-6 text-left focus-visible:outline-teal-600 touch-spring"
                aria-expanded={isOpen}
              >
                <span className="font-display text-base sm:text-lg font-bold text-teal-950 pr-4">
                  {faq.q}
                </span>
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-xl bg-sand-100/80 text-teal-800 font-bold transition-transform duration-200">
                  <svg
                    className={`h-4 w-4 transition-transform ${isOpen ? "rotate-180" : ""}`}
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <polyline points="6 9 12 15 18 9" />
                  </svg>
                </span>
              </button>
              {isOpen && (
                <div className="px-5 pb-5 sm:px-6 sm:pb-6 pt-1 text-xs sm:text-sm text-sand-900/80 leading-relaxed font-medium">
                  <p>{faq.a}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}
