import type { Metadata } from "next";
import { Header } from "../components/Header";
import { Footer } from "../components/landing/Footer";
import { IconShieldCheck, IconAlertTriangle, IconPhone } from "../components/icons";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — PMJAY Advocate",
  description:
    "Terms and conditions for using PMJAY Advocate, including our Care-First Emergency Medical Priority rule and limitation of liability.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-sand-50">
      <Header />

      <main className="mx-auto w-full max-w-4xl flex-1 px-4 sm:px-8 lg:px-10 pt-12 sm:pt-16 pb-16 space-y-10 animate-fade-in">
        {/* Header */}
        <div className="space-y-3">
          <div className="inline-flex items-center gap-2">
            <span className="text-xs sm:text-sm font-bold uppercase tracking-wider text-emerald-700">
              Legal Terms &amp; Conditions
            </span>
          </div>
          <h1 className="font-display text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight-display text-ink-950">
            Terms of Service
          </h1>
          <p className="text-sm sm:text-base text-sand-600 font-medium leading-relaxed">
            Effective Date: August 2026. Please read these terms carefully before using PMJAY Advocate. By using this service, you agree to these terms.
          </p>
        </div>

        {/* Emergency Medical Care Clause — Mandatory Priority */}
        <div className="card p-6 sm:p-7 border-2 border-tier-red-border bg-tier-red-bg space-y-3 shadow-xs">
          <div className="flex items-start gap-3">
            <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-tier-red-icon text-tier-red-text shrink-0 mt-0.5">
              <IconAlertTriangle className="h-4.5 w-4.5" />
            </span>
            <div className="space-y-1.5">
              <h2 className="text-base font-bold text-tier-red-text">
                Mandatory Emergency Medical Priority Clause
              </h2>
              <p className="text-xs sm:text-sm text-tier-red-text leading-relaxed font-medium">
                <strong>Never delay or refuse emergency medical treatment for yourself or a family member to dispute billing charges or verify scheme packages.</strong> In any life-threatening or urgent medical emergency, proceed with hospital admission and treatment immediately. Financial grievances, billing disputes, and insurance pre-authorisation appeals can and should be resolved after the patient is stable and safe.
              </p>
            </div>
          </div>
        </div>

        {/* Section 1: Nature of the Service */}
        <section className="card p-6 sm:p-8 space-y-4">
          <h2 className="text-lg sm:text-xl font-bold text-sand-900 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-sand-100 text-sand-800 text-xs font-bold">
              1
            </span>
            Nature of the Service &amp; Non-Agency
          </h2>
          <div className="space-y-3 text-xs sm:text-sm text-sand-700 leading-relaxed font-medium">
            <p>
              PMJAY Advocate is an independent, open-access, public-interest software application designed to help patients and families understand Ayushman Bharat / PMJAY Health Benefit Packages (HBP).
            </p>
            <ul className="space-y-2 pl-4 list-disc marker:text-emerald-700">
              <li>
                <strong>No Government Affiliation:</strong> PMJAY Advocate is not owned, operated, endorsed by, or affiliated with the National Health Authority (NHA), the Ministry of Health and Family Welfare (MoHFW), State Health Agencies (SHAs), or any empanelled hospital.
              </li>
              <li>
                <strong>No Legal or Medical Representation:</strong> Using this application does not establish an advocate-client relationship, a doctor-patient relationship, or an insurer-beneficiary agency relationship.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 2: Informational Use Only */}
        <section className="card p-6 sm:p-8 space-y-4">
          <h2 className="text-lg sm:text-xl font-bold text-sand-900 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-sand-100 text-sand-800 text-xs font-bold">
              2
            </span>
            Informational and Guidance Purpose Only
          </h2>
          <div className="space-y-3 text-xs sm:text-sm text-sand-700 leading-relaxed font-medium">
            <p>
              All evaluations, tier classifications (Green, Amber, Red, Mixed, Handoff), hospital script suggestions, and draft complaints generated by this software are provided strictly for educational and informational assistance.
            </p>
            <p>
              Formal medical pre-authorisation decisions and clinical package approvals are governed exclusively by empanelled hospital Trust Doctors, State Health Agencies (SHAs), and Third Party Administrators (TPAs) under official NHA rules.
            </p>
          </div>
        </section>

        {/* Section 3: Limitation of Liability */}
        <section className="card p-6 sm:p-8 space-y-4">
          <h2 className="text-lg sm:text-xl font-bold text-sand-900 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-sand-100 text-sand-800 text-xs font-bold">
              3
            </span>
            Limitation of Liability &amp; Warranty Disclaimer
          </h2>
          <div className="space-y-3 text-xs sm:text-sm text-sand-700 leading-relaxed font-medium">
            <p>
              This service is provided on an <strong>&ldquo;AS IS&rdquo;</strong> and <strong>&ldquo;AS AVAILABLE&rdquo;</strong> basis without warranties of any kind, whether express, implied, statutory, or otherwise.
            </p>
            <p>
              To the maximum extent permitted by applicable law, the creators, developers, contributors, and maintainers of PMJAY Advocate shall not be held liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of:
            </p>
            <ul className="space-y-2 pl-4 list-disc marker:text-emerald-700">
              <li>Any decision made or action taken by you or any third party in reliance upon guidance generated by this tool.</li>
              <li>Any refusal, delay, or denial of medical services or insurance reimbursement by a healthcare provider or hospital.</li>
              <li>Any inaccuracies, omissions, or package rate revisions in the underlying government datasets.</li>
            </ul>
          </div>
        </section>

        {/* Section 4: Official Dispute Channels */}
        <section className="card p-6 sm:p-8 space-y-4">
          <h2 className="text-lg sm:text-xl font-bold text-sand-900 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-sand-100 text-sand-800 text-xs font-bold">
              4
            </span>
            Statutory Grievance &amp; Legal Aid Channels
          </h2>
          <div className="space-y-3 text-xs sm:text-sm text-sand-700 leading-relaxed font-medium">
            <p>
              For formal statutory grievances, legal representation, or scheme claims, users are strongly advised to utilize the official government helplines:
            </p>
            <div className="grid sm:grid-cols-2 gap-3 pt-1">
              <div className="p-3.5 rounded-xl bg-sand-50 border border-sand-200 space-y-1">
                <p className="font-bold text-sand-900">National Health Authority Helpline</p>
                <p className="text-xs text-sand-600">Dial <a href="tel:14555" className="font-bold text-emerald-700 underline">14555</a> (Toll-Free, 24/7)</p>
                <p className="text-xs text-sand-500">Official Grievance Portal: cgrms.pmjay.gov.in</p>
              </div>
              <div className="p-3.5 rounded-xl bg-sand-50 border border-sand-200 space-y-1">
                <p className="font-bold text-sand-900">NALSA Free Legal Aid</p>
                <p className="text-xs text-sand-600">Dial <a href="tel:15100" className="font-bold text-emerald-700 underline">15100</a> (Toll-Free)</p>
                <p className="text-xs text-sand-500">Free Para Legal Volunteer &amp; Advocate Assistance</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 5: Governing Law */}
        <section className="card p-6 sm:p-8 space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-sand-900">
            5. Governing Law
          </h2>
          <p className="text-xs sm:text-sm text-sand-600 leading-relaxed font-medium">
            These terms and any disputes arising out of the use of this public-interest tool shall be governed by and construed in accordance with the laws of the Republic of India.
          </p>
        </section>
      </main>

      <Footer />
    </div>
  );
}
